"""Export final transcription to Markdown digital edition."""

from datetime import datetime
from typing import Any, Dict, Optional


def write_markdown(
    final_transcription: Dict[str, Any],
    output_filename: str,
    source_image_name: str,
    assessment_result: Optional[Dict] = None,
    include_metadata: bool = True,
) -> str:
    """Write Markdown file. Returns output_filename."""
    base_name = source_image_name.rsplit("/", 1)[-1].rsplit("\\", 1)[-1]
    base_name = base_name.rsplit(".", 1)[0] if "." in base_name else base_name
    md = []
    md.append(f"# Digital Edition: {base_name}")
    md.append("")
    md.append("*Generated by Agentic Document Processor*")
    md.append(f"*Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")
    md.append("")

    if include_metadata and assessment_result:
        md.append("---")
        md.append("")
        md.append("## Document Information")
        md.append("")
        content = assessment_result.get("content_analysis", {})
        quality = assessment_result.get("quality_metrics", {})
        md.append("| Property | Value |")
        md.append("|----------|-------|")
        md.append(f"| **Source Image** | `{source_image_name}` |")
        md.append(f"| **Script Type** | {content.get('script_type', 'Unknown')} |")
        md.append(f"| **Language** | {content.get('primary_language', 'Unknown')} |")
        md.append(f"| **Period** | {content.get('estimated_period', 'Unknown')} |")
        md.append(f"| **Document Type** | {content.get('document_type', 'Unknown')} |")
        dims = quality.get("dimensions", {})
        md.append(f"| **Dimensions** | {dims.get('width', '?')} × {dims.get('height', '?')} px |")
        md.append("")

    md.append("---")
    md.append("")
    md.append("## Transcription")
    md.append("")

    for region in final_transcription.get("regions", []):
        rtype = region["region_type"]
        text = region.get("text", "")
        status = region.get("status", "unknown")
        if status != "success" or not text:
            continue
        if rtype in ("TitleRegion", "HeadingRegion"):
            md.append(f"## {text}")
        elif rtype == "SubheadingRegion":
            md.append(f"### {text}")
        elif rtype == "PageNumberRegion":
            md.append(f"*[Page: {text}]*")
        elif rtype in ("ImageRegion", "DiagramRegion"):
            md.append(f"> **[{rtype.replace('Region', '')}]**")
            for line in text.split("\n"):
                md.append(f"> {line}")
        elif rtype == "MarginaliaRegion":
            md.append(f"*[Marginalia: {text}]*")
        elif rtype == "TableRegion":
            md.append("**[Table]**")
            md.append("```")
            md.append(text)
            md.append("```")
        else:
            md.append(text)
        md.append("")

    if include_metadata:
        md.append("---")
        md.append("")
        md.append("## Processing Summary")
        md.append("")
        md.append(f"- **Regions Transcribed:** {final_transcription.get('total_regions_transcribed', 0)}")
        md.append(f"- **Regions with Line Coordinates:** {final_transcription.get('regions_with_line_bboxes', 0)}")
        md.append(f"- **Average Confidence:** {final_transcription.get('average_confidence', 0):.2%}")
        md.append("")

    with open(output_filename, "w", encoding="utf-8") as f:
        f.write("\n".join(md))
    return output_filename
